version: '4.3'

services:
  database:
    image: bitnami/postgresql
    container_name: curriculo_db_express
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=curriculo_db
